### ISSUE TITLE
fix scaling for narrow viewport (mobile)

### ISSUE THREAD

**Issue by wavpool** [kiewi16/fitlit#67]
there are currently several issues the the dynamic scaling of elements when viewed on a smaller viewport like a mobile device
- chart sections overlap and spill out of containers
- text can wrap awkwardly
- user address string can be split to display in separate lines

to do - adjust scaling and alignment of elements to accommodate narrower viewports
- charts and sections containing them
- text in user info
- friends section as a whole

**Comment by JWill06** [comment]
Didn't end up doing this due to timeline for project. Kept it useable for desktop use.
